/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    appName: "AI Learning",
    homeBadge: "AI Learning Platform",
    homeTitle: "Smart Educational Assistant",
    homeSubtitle: "Generate exercises, correct student answers, export correction reports, and support learning with artificial intelligence.",
    studentSpace: "Student Space",
    teacherSpace: "Teacher Space",
    studentPanel: "Student Panel",
    teacherPanel: "Teacher Panel",
    teacherFallback: "Teacher",
    dashboard: "Dashboard",
    quizManagement: "Quiz Management",
    studentResults: "Student Results",
    exercises: "Exercises",
    chatbot: "Chatbot",
    history: "History",
    logout: "Logout",
    profile: "Profile",
    language: "Language",
    displayControls: "Display controls",
    close: "Close",
    english: "English",
    french: "French",
    arabic: "Arabic",
    loginTitle: "Welcome Back",
    loginSubtitle: "Login to continue your learning journey",
    email: "Email",
    password: "Password",
    newPassword: "New Password",
    login: "Login",
    createAccount: "Create new account",
    forgotPassword: "Forgot password?",
    registerTitle: "Create Account",
    registerSubtitle: "Register to start using AI Learning Platform",
    fullName: "Full Name",
    register: "Register",
    creating: "Creating...",
    alreadyAccount: "Already have an account?",
    resetTitle: "Reset Password",
    resetSubtitle: "Enter your email and choose a new password",
    updatePassword: "Update Password",
    updating: "Updating...",
    remembered: "Remembered it?",
    backToLogin: "Back to login",
    requiredLogin: "Please enter your email and password",
    requiredAll: "Please fill in all fields",
    requiredReset: "Please enter your email and new password",
    serverError: "Server error",
    dashboardWelcome: "Welcome, Student",
    dashboardSubtitle: "Start learning with AI-powered exercises and corrections.",
    uploadPdfCard: "Upload PDF",
    uploadPdfText: "Upload your course and generate exercises.",
    aiChatbot: "AI Chatbot",
    aiChatbotText: "Ask educational questions only.",
    scores: "Scores",
    scoresText: "View your results and progress.",
    totalQuizzes: "Total quizzes",
    averageScore: "Average score",
    bestScore: "Best score",
    timeSpent: "Time spent",
    noStats: "No quiz results yet",
    quizTitle: "AI Quiz Generator",
    quizSubtitle: "Upload your lesson PDF and generate a personalized quiz.",
    createQuiz: "Create New Quiz",
    uploadLessonPdf: "Upload Lesson PDF",
    assignedTeacher: "Assigned teacher",
    chooseSubjectTeacher: "Choose subject/teacher",
    chooseSubjectTeacherBeforeStart: "Choose subject/teacher before starting quiz.",
    questionCount: "Number of Questions",
    detectedCategory: "Detected category",
    difficultyEasy: "Easy",
    difficultyMedium: "Medium",
    difficultyHard: "Hard",
    difficulty: "Difficulty",
    generateQuiz: "Generate Quiz",
    generating: "Generating...",
    selectPdf: "Please select a PDF",
    generationFailed: "Generation failed. Check backend terminal.",
    quizReady: "Your quiz is ready",
    quizReadyText: "Review the lesson summary or start the quiz when you are ready.",
    startQuiz: "Start Quiz",
    lessonSummary: "View Lesson Summary",
    backToChoices: "Back to Choices",
    summaryTitle: "Lesson Summary",
    keyConcepts: "Key concepts",
    importantNotes: "Important notes",
    importantNoteBody: "Use the lesson summary to prepare, then answer each question in your own words.",
    question: "Question",
    yourAnswer: "Your answer",
    back: "Back",
    next: "Next",
    finishQuiz: "Finish Quiz",
    saving: "Saving result...",
    correctionFailed: "Correction failed. Check backend terminal.",
    resultTitle: "Correction Result",
    correct: "Correct",
    incorrect: "Incorrect",
    aiFeedback: "AI Feedback",
    correctAnswer: "Correct answer",
    downloadPdf: "Download Correction PDF",
    downloading: "Downloading...",
    retakeQuiz: "Retake Quiz",
    lessonPreview: "Lesson Preview",
    noAnswer: "No answer provided",
    resultSaved: "Result saved in MySQL.",
    excellentWork: "Excellent work!",
    goodProgress: "Good progress",
    keepImproving: "Keep improving",
    mediumMessage: "You are close. Review the missed points and try again.",
    lowMessage: "Keep practicing. Every attempt makes the next one easier.",
    pdfFailed: "PDF download failed",
    noExercisesGenerated: "No exercises were generated",
    studentFallback: "Student",
    lessonFallback: "lesson",
    minutesShort: "m",
    secondsShort: "s",
    hoursShort: "h",
    quizProgressLabel: "Quiz progress",
    yourQuizzes: "Your Quizzes",
    recentQuizzes: "Recent quizzes",
    completed: "completed",
    completedDate: "Completed date",
    retakeQuizAction: "Retake Quiz",
    viewCorrection: "View Correction",
    resultsAction: "Results",
    share: "Share",
    viewDetails: "View details",
    historyTitle: "Quiz History",
    historySubtitle: "Review all completed quizzes and corrections.",
    correctionDetails: "Correction details",
    scoreSummary: "Score summary",
    completedOn: "Completed on",
    resultCopied: "Result copied successfully.",
    shareLinkCopied: "Shareable quiz link copied successfully.",
    sharedQuizTitle: "Shared Quiz",
    guestMode: "Guest Mode",
    guestQuizTitle: "Guest Quiz",
    guestQuizSubtitle: "Upload a lesson PDF, generate a quiz, and get instant correction without logging in.",
    retakeQuizTitle: "Retake Quiz",
    loadingQuiz: "Loading quiz...",
    quizUnavailable: "This quiz is not available.",
    shareText: "I completed a quiz in {category} with score {score}% on AI Learning Platform.",
    noQuizzesYet: "No completed quizzes yet.",
    chatbotTitle: "Learnix AI Assistant",
    chatbotSubtitle: "Ask questions, upload lessons and learn smarter with AI.",
    chatWelcome: "Hello.\nI can help with your lessons, summarize PDFs, explain concepts, and solve exercises.\nHow can I help you today?",
    chatPlaceholder: "Ask an educational question...",
    send: "Send",
    uploadPdf: "Upload PDF",
    uploadImage: "Upload Image",
    takePhoto: "Take Photo",
    microphone: "Microphone",
    clearChat: "Clear chat",
    aiThinking: "AI is answering...",
    uploadedFile: "Uploaded file",
    fileReady: "Lesson uploaded. Ask me a question about it.",
    lessonContextReady: "Lesson context ready",
    chatError: "I could not answer right now. Please try again.",
    chatUploadFailed: "File upload failed. Please try again.",
    imageUnavailable: "Image analysis is not available yet.",
    voiceUnsupported: "Voice input is not supported in this browser.",
    cameraUnsupported: "Camera is not supported or permission was denied.",
    capture: "Capture",
    settings: "Settings",
    settingsSubtitle: "Personalize your Learnix AI study workspace.",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    workspaceKicker: "AI Study Workspace",
    premiumTitle: "Learnix AI Premium",
    premiumSubtitle: "Unlimited AI study assistance",
    upgradePremium: "Upgrade Premium",
    premiumModalTitle: "Upgrade your study workspace",
    premiumModalBody: "Choose a demo plan and enter payment details. No real payment will be processed.",
    premiumPricing: "Premium pricing",
    monthly: "Monthly",
    yearly: "Yearly",
    cardholderName: "Cardholder name",
    cardNumber: "Card number",
    expiryDate: "Expiry date",
    cvv: "CVV",
    pay: "Pay",
    maybeLater: "Maybe later",
    premiumDemoActivated: "Premium demo activated.",
    profileSettings: "Profile Settings",
    profileSettingsText: "Manage the information shown in your Learnix AI account.",
    languageSettings: "Language Settings",
    interfaceLanguage: "Interface language",
    languageSettingsText: "Choose the language used across Learnix AI.",
    themeSettings: "Theme Settings",
    displayMode: "Display mode",
    themeSettingsText: "Switch between a clean light workspace and a dark blue workspace.",
    security: "Security",
    changePassword: "Change password",
    passwordText: "Prepare a new password for your student account.",
    currentPassword: "Current password",
    savePassword: "Save password",
    passwordSaved: "Password saved successfully.",
    aiPreferences: "AI Preferences",
    preferredAiLanguage: "Preferred AI language",
    preferredAiLanguageText: "This uses the same app language for AI explanations.",
    premiumSettingsText: "Unlock more practice, richer uploads, and faster feedback.",
    unlimitedQuizzes: "Unlimited quizzes",
    unlimitedChatbot: "Unlimited AI chatbot",
    uploadSupport: "PDF, image, and camera support",
    priorityCorrections: "Priority corrections",
    noEmailSaved: "No email saved for this session.",
    name: "Name",
    phone: "Phone",
    studentName: "Student name",
    enterCurrentPassword: "Enter current password",
    enterNewPassword: "Enter new password",
  },
  fr: {
    appName: "AI Learning",
    homeBadge: "Plateforme AI Learning",
    homeTitle: "Assistant éducatif intelligent",
    homeSubtitle: "Générez des exercices, corrigez les réponses, exportez des rapports et soutenez l'apprentissage avec l'intelligence artificielle.",
    studentSpace: "Espace étudiant",
    teacherSpace: "Espace enseignant",
    studentPanel: "Espace étudiant",
    teacherPanel: "Espace enseignant",
    teacherFallback: "Enseignant",
    dashboard: "Tableau de bord",
    quizManagement: "Gestion des quiz",
    studentResults: "Résultats des étudiants",
    exercises: "Exercices",
    chatbot: "Assistant IA",
    history: "Historique",
    logout: "Déconnexion",
    profile: "Profil",
    language: "Langue",
    displayControls: "Contrôles d'affichage",
    close: "Fermer",
    english: "Anglais",
    french: "Français",
    arabic: "Arabe",
    loginTitle: "Bon retour",
    loginSubtitle: "Connectez-vous pour continuer votre apprentissage",
    email: "Adresse e-mail",
    password: "Mot de passe",
    newPassword: "Nouveau mot de passe",
    login: "Connexion",
    createAccount: "Créer un compte",
    forgotPassword: "Mot de passe oublié ?",
    registerTitle: "Créer un compte",
    registerSubtitle: "Inscrivez-vous pour utiliser Learnix AI",
    fullName: "Nom complet",
    register: "Inscription",
    creating: "Création...",
    alreadyAccount: "Vous avez déjà un compte ?",
    resetTitle: "Réinitialiser le mot de passe",
    resetSubtitle: "Entrez votre adresse e-mail et choisissez un nouveau mot de passe",
    updatePassword: "Mettre à jour",
    updating: "Mise à jour...",
    remembered: "Vous vous en souvenez ?",
    backToLogin: "Retour à la connexion",
    requiredLogin: "Veuillez entrer votre adresse e-mail et votre mot de passe",
    requiredAll: "Veuillez remplir tous les champs",
    requiredReset: "Veuillez entrer votre adresse e-mail et votre nouveau mot de passe",
    serverError: "Erreur serveur",
    dashboardWelcome: "Bienvenue",
    dashboardSubtitle: "Apprenez avec des exercices et corrections alimentés par l'IA.",
    uploadPdfCard: "Importer un PDF",
    uploadPdfText: "Importez votre cours et générez des exercices.",
    aiChatbot: "Assistant IA",
    aiChatbotText: "Posez uniquement des questions éducatives.",
    scores: "Résultats",
    scoresText: "Consultez vos résultats et votre progression.",
    totalQuizzes: "Nombre total de quiz",
    averageScore: "Score moyen",
    bestScore: "Meilleur score",
    timeSpent: "Temps passé",
    noStats: "Aucun résultat pour le moment",
    quizTitle: "Générateur de quiz IA",
    quizSubtitle: "Importez votre PDF de cours et générez un quiz personnalisé.",
    createQuiz: "Créer un quiz",
    uploadLessonPdf: "Importer le PDF",
    assignedTeacher: "Enseignant assigné",
    chooseSubjectTeacher: "Choisir une matière ou un enseignant",
    chooseSubjectTeacherBeforeStart: "Choisissez une matière ou un enseignant avant de commencer le quiz.",
    questionCount: "Nombre de questions",
    detectedCategory: "Catégorie détectée",
    difficultyEasy: "Facile",
    difficultyMedium: "Moyen",
    difficultyHard: "Difficile",
    difficulty: "Difficulté",
    generateQuiz: "Générer le quiz",
    generating: "Génération...",
    selectPdf: "Veuillez sélectionner un PDF",
    generationFailed: "Échec de la génération. Vérifiez le serveur.",
    quizReady: "Votre quiz est prêt",
    quizReadyText: "Révisez le résumé du cours ou commencez le quiz.",
    startQuiz: "Commencer le quiz",
    lessonSummary: "Voir le résumé du cours",
    backToChoices: "Retour aux choix",
    summaryTitle: "Résumé du cours",
    keyConcepts: "Concepts clés",
    importantNotes: "Notes importantes",
    importantNoteBody: "Utilisez le résumé du cours pour vous préparer, puis répondez à chaque question avec vos propres mots.",
    question: "Question",
    yourAnswer: "Votre réponse",
    back: "Retour",
    next: "Suivant",
    finishQuiz: "Terminer le quiz",
    saving: "Enregistrement...",
    correctionFailed: "Échec de la correction. Vérifiez le serveur.",
    resultTitle: "Résultat de correction",
    correct: "Correcte",
    incorrect: "Incorrecte",
    aiFeedback: "Retour de l'IA",
    correctAnswer: "Réponse correcte",
    downloadPdf: "Télécharger le PDF",
    downloading: "Téléchargement...",
    retakeQuiz: "Refaire le quiz",
    lessonPreview: "Aperçu du cours",
    noAnswer: "Aucune réponse",
    resultSaved: "Résultat enregistré.",
    excellentWork: "Excellent travail !",
    goodProgress: "Bonne progression",
    keepImproving: "Continuez à progresser",
    mediumMessage: "Vous êtes proche. Revoyez les points manqués puis réessayez.",
    lowMessage: "Continuez à pratiquer. Chaque essai facilite le suivant.",
    pdfFailed: "Échec du téléchargement PDF",
    noExercisesGenerated: "Aucun exercice n'a été généré",
    studentFallback: "Étudiant",
    lessonFallback: "leçon",
    minutesShort: "min",
    secondsShort: "s",
    hoursShort: "h",
    quizProgressLabel: "Progression du quiz",
    yourQuizzes: "Vos quiz",
    recentQuizzes: "Quiz récents",
    completed: "terminé",
    completedDate: "Date de fin",
    retakeQuizAction: "Refaire le quiz",
    viewCorrection: "Voir la correction",
    resultsAction: "Résultats",
    share: "Partager",
    viewDetails: "Voir les détails",
    historyTitle: "Historique des quiz",
    historySubtitle: "Consultez tous les quiz terminés et leurs corrections.",
    correctionDetails: "Détails de correction",
    scoreSummary: "Résumé du score",
    completedOn: "Terminé le",
    resultCopied: "Résultat copié dans le presse-papiers.",
    shareLinkCopied: "Lien partageable du quiz copié avec succès.",
    sharedQuizTitle: "Quiz partagé",
    guestMode: "Mode invité",
    guestQuizTitle: "Quiz invité",
    guestQuizSubtitle: "Importez un PDF de cours, générez un quiz et obtenez une correction instantanée sans connexion.",
    retakeQuizTitle: "Refaire le quiz",
    loadingQuiz: "Chargement du quiz...",
    quizUnavailable: "Ce quiz n'est pas disponible.",
    shareText: "J'ai terminé un quiz en {category} avec un score de {score}% sur Learnix AI.",
    noQuizzesYet: "Aucun quiz terminé pour le moment.",
    chatbotTitle: "Assistant Learnix AI",
    chatbotSubtitle: "Posez des questions, importez des leçons et apprenez plus efficacement avec l'IA.",
    chatWelcome: "Bonjour.\nJe peux vous aider avec vos cours, résumer des PDF, expliquer des notions et résoudre des exercices.\nComment puis-je vous aider aujourd'hui ?",
    chatPlaceholder: "Posez une question éducative...",
    send: "Envoyer",
    uploadPdf: "Importer un PDF",
    uploadImage: "Importer image",
    takePhoto: "Prendre une photo",
    microphone: "Microphone",
    clearChat: "Effacer la conversation",
    aiThinking: "L'IA répond...",
    uploadedFile: "Fichier importé",
    fileReady: "Leçon importée. Posez-moi une question à son sujet.",
    lessonContextReady: "Contexte du cours prêt",
    chatError: "Je ne peux pas répondre pour le moment. Veuillez réessayer.",
    chatUploadFailed: "Échec de l'importation. Veuillez réessayer.",
    imageUnavailable: "L'analyse d'image n'est pas encore disponible.",
    voiceUnsupported: "La saisie vocale n'est pas prise en charge par ce navigateur.",
    cameraUnsupported: "La caméra n'est pas prise en charge ou l'autorisation a été refusée.",
    capture: "Capturer",
    settings: "Paramètres",
    settingsSubtitle: "Personnalisez votre espace d'étude Learnix AI.",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    workspaceKicker: "Espace d'étude IA",
    premiumTitle: "Learnix AI Premium",
    premiumSubtitle: "Assistance d'étude IA illimitée",
    upgradePremium: "Passer Premium",
    premiumModalTitle: "Améliorez votre espace d'étude",
    premiumModalBody: "Choisissez une formule de démonstration et saisissez les détails de paiement. Aucun vrai paiement ne sera traité.",
    premiumPricing: "Tarifs Premium",
    monthly: "Mensuel",
    yearly: "Annuel",
    cardholderName: "Nom du titulaire",
    cardNumber: "Numéro de carte",
    expiryDate: "Date d'expiration",
    cvv: "CVV",
    pay: "Payer",
    maybeLater: "Plus tard",
    premiumDemoActivated: "Démo Premium activée.",
    profileSettings: "Paramètres du profil",
    profileSettingsText: "Gérez les informations affichées dans votre compte Learnix AI.",
    languageSettings: "Paramètres de langue",
    interfaceLanguage: "Langue de l'interface",
    languageSettingsText: "Choisissez la langue utilisée dans Learnix AI.",
    themeSettings: "Paramètres du thème",
    displayMode: "Mode d'affichage",
    themeSettingsText: "Passez d'un espace clair à un espace bleu sombre.",
    security: "Sécurité",
    changePassword: "Changer le mot de passe",
    passwordText: "Préparez un nouveau mot de passe pour votre compte.",
    currentPassword: "Mot de passe actuel",
    savePassword: "Enregistrer le mot de passe",
    passwordSaved: "Mot de passe enregistré avec succès.",
    aiPreferences: "Préférences IA",
    preferredAiLanguage: "Langue IA préférée",
    preferredAiLanguageText: "La même langue globale est utilisée pour les explications IA.",
    premiumSettingsText: "Débloquez plus de pratique, d'imports et de retours rapides.",
    unlimitedQuizzes: "Quiz illimités",
    unlimitedChatbot: "Chatbot IA illimité",
    uploadSupport: "Prise en charge des PDF, des images et de la caméra",
    priorityCorrections: "Corrections prioritaires",
    noEmailSaved: "Aucune adresse e-mail enregistrée pour cette session.",
    name: "Nom",
    phone: "Téléphone",
    studentName: "Nom de l'étudiant",
    enterCurrentPassword: "Entrez le mot de passe actuel",
    enterNewPassword: "Entrez le nouveau mot de passe",
  },
  ar: {
    appName: "AI Learning",
    homeBadge: "منصة AI Learning",
    homeTitle: "مساعد تعليمي ذكي",
    homeSubtitle: "أنشئ تمارين، صحح إجابات الطلاب، صدر تقارير التصحيح، وادعم التعلم بالذكاء الاصطناعي.",
    studentSpace: "مساحة الطالب",
    teacherSpace: "مساحة المعلم",
    studentPanel: "لوحة الطالب",
    teacherPanel: "لوحة المعلم",
    teacherFallback: "معلم",
    dashboard: "لوحة التحكم",
    quizManagement: "إدارة الاختبارات",
    studentResults: "نتائج الطلاب",
    exercises: "التمارين",
    chatbot: "المساعد",
    history: "السجل",
    logout: "تسجيل الخروج",
    profile: "الملف الشخصي",
    language: "اللغة",
    displayControls: "عناصر التحكم في العرض",
    close: "إغلاق",
    english: "الإنجليزية",
    french: "الفرنسية",
    arabic: "العربية",
    loginTitle: "مرحبا بعودتك",
    loginSubtitle: "سجل الدخول لمتابعة التعلم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    newPassword: "كلمة مرور جديدة",
    login: "دخول",
    createAccount: "إنشاء حساب",
    forgotPassword: "نسيت كلمة المرور؟",
    registerTitle: "إنشاء حساب",
    registerSubtitle: "سجل لاستخدام منصة التعلم بالذكاء الاصطناعي",
    fullName: "الاسم الكامل",
    register: "تسجيل",
    creating: "جار الإنشاء...",
    alreadyAccount: "لديك حساب؟",
    resetTitle: "إعادة تعيين كلمة المرور",
    resetSubtitle: "أدخل بريدك واختر كلمة مرور جديدة",
    updatePassword: "تحديث كلمة المرور",
    updating: "جار التحديث...",
    remembered: "تذكرتها؟",
    backToLogin: "العودة للدخول",
    requiredLogin: "أدخل البريد وكلمة المرور",
    requiredAll: "يرجى ملء كل الحقول",
    requiredReset: "أدخل البريد وكلمة المرور الجديدة",
    serverError: "خطأ في الخادم",
    dashboardWelcome: "مرحبا بالطالب",
    dashboardSubtitle: "ابدأ التعلم مع تمارين وتصحيحات بالذكاء الاصطناعي.",
    uploadPdfCard: "رفع PDF",
    uploadPdfText: "ارفع درسك وأنشئ تمارين.",
    aiChatbot: "مساعد الذكاء الاصطناعي",
    aiChatbotText: "اطرح أسئلة تعليمية فقط.",
    scores: "النتائج",
    scoresText: "اعرض نتائجك وتقدمك.",
    totalQuizzes: "إجمالي الاختبارات",
    averageScore: "المعدل",
    bestScore: "أفضل نتيجة",
    timeSpent: "الوقت المستغرق",
    noStats: "لا توجد نتائج بعد",
    quizTitle: "مولد الاختبارات بالذكاء الاصطناعي",
    quizSubtitle: "ارفع ملف الدرس PDF وأنشئ اختبارا مخصصا.",
    createQuiz: "إنشاء اختبار جديد",
    uploadLessonPdf: "رفع ملف PDF",
    assignedTeacher: "المعلم المعين",
    chooseSubjectTeacher: "اختر المادة أو المعلم",
    chooseSubjectTeacherBeforeStart: "اختر المادة أو المعلم قبل بدء الاختبار.",
    questionCount: "عدد الأسئلة",
    detectedCategory: "الفئة المكتشفة",
    difficultyEasy: "سهل",
    difficultyMedium: "متوسط",
    difficultyHard: "صعب",
    difficulty: "المستوى",
    generateQuiz: "إنشاء الاختبار",
    generating: "جار الإنشاء...",
    selectPdf: "يرجى اختيار ملف PDF",
    generationFailed: "فشل الإنشاء. تحقق من الخادم.",
    quizReady: "الاختبار جاهز",
    quizReadyText: "راجع ملخص الدرس أو ابدأ الاختبار عندما تكون جاهزا.",
    startQuiz: "بدء الاختبار",
    lessonSummary: "عرض ملخص الدرس",
    backToChoices: "العودة للاختيارات",
    summaryTitle: "ملخص الدرس",
    keyConcepts: "المفاهيم الأساسية",
    importantNotes: "ملاحظات مهمة",
    importantNoteBody: "استخدم ملخص الدرس للاستعداد، ثم أجب عن كل سؤال بكلماتك الخاصة.",
    question: "السؤال",
    yourAnswer: "إجابتك",
    back: "السابق",
    next: "التالي",
    finishQuiz: "إنهاء الاختبار",
    saving: "جار حفظ النتيجة...",
    correctionFailed: "فشل التصحيح. تحقق من الخادم.",
    resultTitle: "نتيجة التصحيح",
    correct: "صحيح",
    incorrect: "خطأ",
    aiFeedback: "ملاحظات الذكاء الاصطناعي",
    correctAnswer: "الإجابة الصحيحة",
    downloadPdf: "تحميل PDF التصحيح",
    downloading: "جار التحميل...",
    retakeQuiz: "إعادة الاختبار",
    lessonPreview: "معاينة الدرس",
    noAnswer: "لا توجد إجابة",
    resultSaved: "تم حفظ النتيجة.",
    excellentWork: "عمل ممتاز!",
    goodProgress: "تقدم جيد",
    keepImproving: "استمر في التحسن",
    mediumMessage: "أنت قريب. راجع النقاط الفائتة وحاول مرة أخرى.",
    lowMessage: "واصل التدريب. كل محاولة تجعل التالية أسهل.",
    pdfFailed: "فشل تحميل PDF",
    noExercisesGenerated: "لم يتم إنشاء تمارين",
    studentFallback: "طالب",
    lessonFallback: "درس",
    minutesShort: "د",
    secondsShort: "ث",
    hoursShort: "س",
    quizProgressLabel: "تقدم الاختبار",
    yourQuizzes: "اختباراتي",
    recentQuizzes: "الاختبارات الأخيرة",
    completed: "مكتمل",
    completedDate: "تاريخ الإكمال",
    retakeQuizAction: "إعادة الاختبار",
    viewCorrection: "عرض التصحيح",
    resultsAction: "النتائج",
    share: "مشاركة",
    viewDetails: "عرض التفاصيل",
    historyTitle: "سجل الاختبارات",
    historySubtitle: "راجع كل الاختبارات المكتملة والتصحيحات.",
    correctionDetails: "تفاصيل التصحيح",
    scoreSummary: "ملخص النتيجة",
    completedOn: "اكتمل في",
    resultCopied: "تم نسخ النتيجة إلى الحافظة.",
    shareLinkCopied: "تم نسخ رابط الاختبار القابل للمشاركة بنجاح.",
    sharedQuizTitle: "اختبار مشترك",
    guestMode: "وضع الضيف",
    guestQuizTitle: "اختبار الضيف",
    guestQuizSubtitle: "ارفع ملف درس PDF وأنشئ اختبارا واحصل على التصحيح فورا دون تسجيل الدخول.",
    retakeQuizTitle: "إعادة الاختبار",
    loadingQuiz: "جار تحميل الاختبار...",
    quizUnavailable: "هذا الاختبار غير متاح.",
    shareText: "أكملت اختبارا في {category} بنتيجة {score}% على منصة Learnix AI.",
    noQuizzesYet: "لا توجد اختبارات مكتملة بعد.",
    chatbotTitle: "مساعد Learnix AI",
    chatbotSubtitle: "اطرح الأسئلة وارفع الدروس وتعلم بذكاء أكثر مع الذكاء الاصطناعي.",
    chatWelcome: "مرحبا.\nأستطيع مساعدتك في دروسك، وتلخيص ملفات PDF، وشرح المفاهيم، وحل التمارين.\nكيف يمكنني مساعدتك اليوم؟",
    chatPlaceholder: "اكتب سؤالا تعليميا...",
    send: "إرسال",
    uploadPdf: "رفع PDF",
    uploadImage: "رفع صورة",
    takePhoto: "التقاط صورة",
    microphone: "الميكروفون",
    clearChat: "مسح المحادثة",
    aiThinking: "الذكاء الاصطناعي يجيب...",
    uploadedFile: "الملف المرفوع",
    fileReady: "تم رفع الدرس. اسألني عنه.",
    lessonContextReady: "سياق الدرس جاهز",
    chatError: "تعذر الحصول على إجابة الآن. حاول مرة أخرى.",
    chatUploadFailed: "فشل رفع الملف. حاول مرة أخرى.",
    imageUnavailable: "تحليل الصور غير متاح حاليا.",
    voiceUnsupported: "الإدخال الصوتي غير مدعوم في هذا المتصفح.",
    cameraUnsupported: "الكاميرا غير مدعومة أو تم رفض الإذن.",
    capture: "التقاط",
    settings: "الإعدادات",
    settingsSubtitle: "خصص مساحة الدراسة في Learnix AI.",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    workspaceKicker: "مساحة دراسة بالذكاء الاصطناعي",
    premiumTitle: "Learnix AI Premium",
    premiumSubtitle: "مساعدة دراسية غير محدودة بالذكاء الاصطناعي",
    upgradePremium: "ترقية إلى Premium",
    premiumModalTitle: "قم بترقية مساحة الدراسة",
    premiumModalBody: "اختر خطة تجريبية وأدخل بيانات الدفع. لن تتم معالجة أي دفع حقيقي.",
    premiumPricing: "أسعار الباقة المميزة",
    monthly: "شهري",
    yearly: "سنوي",
    cardholderName: "اسم حامل البطاقة",
    cardNumber: "رقم البطاقة",
    expiryDate: "تاريخ الانتهاء",
    cvv: "CVV",
    pay: "دفع",
    maybeLater: "لاحقا",
    premiumDemoActivated: "تم تفعيل العرض التجريبي المميز.",
    profileSettings: "إعدادات الملف الشخصي",
    profileSettingsText: "أدر المعلومات المعروضة في حساب Learnix AI.",
    languageSettings: "إعدادات اللغة",
    interfaceLanguage: "لغة الواجهة",
    languageSettingsText: "اختر اللغة المستخدمة في Learnix AI.",
    themeSettings: "إعدادات المظهر",
    displayMode: "وضع العرض",
    themeSettingsText: "بدل بين مساحة فاتحة ومساحة زرقاء داكنة.",
    security: "الأمان",
    changePassword: "تغيير كلمة المرور",
    passwordText: "جهز كلمة مرور جديدة لحسابك.",
    currentPassword: "كلمة المرور الحالية",
    savePassword: "حفظ كلمة المرور",
    passwordSaved: "تم حفظ كلمة المرور بنجاح.",
    aiPreferences: "تفضيلات الذكاء الاصطناعي",
    preferredAiLanguage: "لغة الذكاء الاصطناعي المفضلة",
    preferredAiLanguageText: "تستخدم التفسيرات نفس لغة التطبيق العامة.",
    premiumSettingsText: "افتح المزيد من التدريب والرفع والتصحيح الأسرع.",
    unlimitedQuizzes: "اختبارات غير محدودة",
    unlimitedChatbot: "مساعد ذكاء اصطناعي غير محدود",
    uploadSupport: "دعم PDF والصور والكاميرا",
    priorityCorrections: "تصحيحات ذات أولوية",
    noEmailSaved: "لا يوجد بريد إلكتروني محفوظ لهذه الجلسة.",
    name: "الاسم",
    phone: "الهاتف",
    studentName: "اسم الطالب",
    enterCurrentPassword: "أدخل كلمة المرور الحالية",
    enterNewPassword: "أدخل كلمة المرور الجديدة",
  },
};

const LanguageContext = createContext(null);

const translationOverrides = {
  en: {
    duration: "Duration",
    quickActions: "Quick actions",
    summarizePdf: "Summarize PDF",
    generateExercises: "Generate Exercises",
    explainChapter: "Explain Chapter",
    uploadReadyStatus: "Ready",
    uploadingStatus: "Uploading...",
    uploadFailedStatus: "Upload failed",
    pages: "pages",
    imageContextReady: "Image ready",
  },
  fr: {
    appName: "Learnix AI",
    homeBadge: "Plateforme Learnix AI",
    homeTitle: "Assistant pédagogique intelligent",
    homeSubtitle: "Créez des exercices, corrigez les réponses, exportez des rapports d'évaluation et accompagnez l'apprentissage avec l'IA.",
    studentSpace: "Espace élève",
    teacherSpace: "Espace enseignant",
    studentPanel: "Espace élève",
    teacherPanel: "Espace enseignant",
    studentResults: "Résultats des élèves",
    logout: "Déconnexion",
    displayControls: "Contrôles d'affichage",
    french: "Français",
    loginTitle: "Bon retour",
    createAccount: "Créer un compte",
    registerTitle: "Créer un compte",
    creating: "Création...",
    alreadyAccount: "Vous avez déjà un compte ?",
    backToLogin: "Retour à la connexion",
    dashboardWelcome: "Bienvenue",
    dashboardSubtitle: "Progressez avec des exercices personnalisés, des corrections instantanées et un suivi clair de vos résultats.",
    uploadPdfCard: "Importer un PDF",
    uploadPdfText: "Importez votre cours pour générer des activités adaptées.",
    aiChatbot: "Assistant IA",
    aiChatbotText: "Posez des questions pédagogiques et travaillez à partir de vos documents.",
    scores: "Résultats",
    scoresText: "Consultez vos scores et votre progression.",
    totalQuizzes: "Quiz terminés",
    averageScore: "Score moyen",
    bestScore: "Meilleur score",
    timeSpent: "Temps de travail",
    noStats: "Aucun résultat disponible pour le moment",
    quizTitle: "Générateur de quiz IA",
    quizSubtitle: "Importez un support de cours au format PDF et générez un quiz personnalisé.",
    createQuiz: "Créer un quiz",
    uploadLessonPdf: "Importer le PDF du cours",
    assignedTeacher: "Enseignant référent",
    chooseSubjectTeacher: "Choisir une matière ou un enseignant",
    chooseSubjectTeacherBeforeStart: "Sélectionnez une matière ou un enseignant avant de commencer le quiz.",
    questionCount: "Nombre de questions",
    detectedCategory: "Matière détectée",
    difficultyEasy: "Facile",
    difficultyMedium: "Intermédiaire",
    difficultyHard: "Difficile",
    difficulty: "Niveau de difficulté",
    generateQuiz: "Générer le quiz",
    generating: "Génération en cours...",
    selectPdf: "Veuillez sélectionner un fichier PDF",
    generationFailed: "La génération a échoué. Vérifiez le serveur et réessayez.",
    quizReady: "Votre quiz est prêt",
    quizReadyText: "Consultez le résumé du cours ou lancez le quiz lorsque vous êtes prêt.",
    startQuiz: "Commencer le quiz",
    lessonSummary: "Consulter le résumé du cours",
    backToChoices: "Retour aux options",
    summaryTitle: "Résumé du cours",
    keyConcepts: "Notions clés",
    importantNotes: "Points importants",
    importantNoteBody: "Appuyez-vous sur le résumé du cours, puis répondez avec vos propres mots.",
    yourAnswer: "Votre réponse",
    finishQuiz: "Terminer le quiz",
    saving: "Enregistrement du résultat...",
    correctionFailed: "La correction a échoué. Veuillez réessayer.",
    resultTitle: "Résultat de la correction",
    correct: "Correct",
    incorrect: "À revoir",
    aiFeedback: "Retour de l'IA",
    correctAnswer: "Réponse attendue",
    downloadPdf: "Télécharger le rapport PDF",
    downloading: "Téléchargement en cours...",
    retakeQuiz: "Refaire le quiz",
    lessonPreview: "Aperçu du cours",
    noAnswer: "Aucune réponse fournie",
    resultSaved: "Résultat enregistré.",
    excellentWork: "Excellent travail !",
    goodProgress: "Bonne progression",
    keepImproving: "Continuez à progresser",
    mediumMessage: "Vous êtes sur la bonne voie. Revoyez les points à consolider puis réessayez.",
    lowMessage: "Continuez à vous entraîner. Chaque tentative vous rapproche de la maîtrise.",
    pdfFailed: "Le téléchargement du PDF a échoué",
    noExercisesGenerated: "Aucun exercice n'a été généré",
    studentFallback: "Élève",
    lessonFallback: "cours",
    quizProgressLabel: "Progression du quiz",
    yourQuizzes: "Vos quiz",
    recentQuizzes: "Quiz récents",
    completed: "terminé",
    completedDate: "Date de réalisation",
    retakeQuizAction: "Refaire",
    viewCorrection: "Voir la correction",
    resultsAction: "Résultats",
    viewDetails: "Voir les détails",
    historyTitle: "Historique des quiz",
    historySubtitle: "Retrouvez vos quiz terminés, vos scores, vos durées et vos corrections.",
    correctionDetails: "Correction détaillée",
    scoreSummary: "Synthèse du score",
    completedOn: "Terminé le",
    shareLinkCopied: "Lien de partage copié.",
    guestQuizSubtitle: "Importez un PDF de cours, générez un quiz et obtenez une correction instantanée sans connexion.",
    quizUnavailable: "Ce quiz n'est pas disponible.",
    noQuizzesYet: "Aucun quiz terminé pour le moment.",
    chatbotTitle: "Assistant Learnix AI",
    chatbotSubtitle: "Posez vos questions, importez vos cours et étudiez plus efficacement avec l'IA.",
    chatWelcome: "Bonjour.\nJe peux vous aider à comprendre vos cours, résumer des PDF, expliquer des notions et créer des exercices.\nQue souhaitez-vous travailler aujourd'hui ?",
    chatPlaceholder: "Posez une question pédagogique...",
    uploadPdf: "Importer un PDF",
    uploadImage: "Importer une image",
    takePhoto: "Prendre une photo",
    clearChat: "Effacer la conversation",
    aiThinking: "L'IA prépare sa réponse...",
    uploadedFile: "Fichier importé",
    lessonContextReady: "Cours prêt",
    imageContextReady: "Image prête",
    chatError: "Je ne peux pas répondre pour le moment. Veuillez réessayer.",
    chatUploadFailed: "L'importation a échoué. Veuillez réessayer.",
    imageUnavailable: "L'analyse d'image n'est pas encore disponible.",
    voiceUnsupported: "La saisie vocale n'est pas disponible dans ce navigateur.",
    cameraUnsupported: "La caméra n'est pas disponible ou l'autorisation a été refusée.",
    capture: "Capturer",
    settings: "Paramètres",
    settingsSubtitle: "Personnalisez votre espace d'étude Learnix AI.",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    duration: "Durée",
    quickActions: "Actions rapides",
    summarizePdf: "Résumer le PDF",
    generateExercises: "Générer des exercices",
    explainChapter: "Expliquer le chapitre",
    uploadReadyStatus: "Prêt",
    uploadingStatus: "Importation...",
    uploadFailedStatus: "Échec de l'importation",
    pages: "pages",
  },
  ar: {
    duration: "المدة",
    quickActions: "إجراءات سريعة",
    summarizePdf: "تلخيص PDF",
    generateExercises: "إنشاء تمارين",
    explainChapter: "شرح الفصل",
    uploadReadyStatus: "جاهز",
    uploadingStatus: "جار الرفع...",
    uploadFailedStatus: "فشل الرفع",
    pages: "صفحات",
    imageContextReady: "الصورة جاهزة",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem("language") || "en"
  );

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo(() => {
    const t = {
      ...translations.en,
      ...(translations[language] || {}),
      ...(translationOverrides[language] || {}),
    };
    return {
      language,
      setLanguage: setLanguageState,
      t,
      dir: language === "ar" ? "rtl" : "ltr",
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
